FROM alpine

LABEL maintainer="Benjamin Carlier <bcarlier@student.42.fr>"

RUN apk add --update sl

CMD ["sl", "-e"]

# To build : docker build -t train_img .
# To run : docker run -it --rm --name tchoutchou train_img
